public final class an
{
  public static String[] a;
  public static String[] b;
  public static String c;
  public static String d;
  public static String e;
  public static String f;
  public static String g;
  public static String h;
  public static String i;
  public static String[] j;
  public static String k;
  public static String l;
  public static String m;
  public static String n;
  public static String o;
  public static String p;
  public static String q;
  public static String r;
  public static String s;
  public static String t;
  public static String u;
  public static String v;
  public static String w;
  public static String x;
  public static String y;
  public static String z;
  public static String[] aa;
  public static String ab;
  public static String[] ac;
  public static String ad;
  public static String ae;
  public static String af;
  public static String[] ag;
  public static String ah;
  public static String ai;
  public static String aj;
  public static String[][] ak;
  public static String al;
  public static String am;
  public static String[] an;
  public static String ao;
  public static String ap;
  public static String aq;
  public static String ar;
  public static String as;
  public static String at;
  public static String[] au;
  public static String av;
  public static String aw;
  public static String ax;
  public static String ay;
  public static String az;
  public static String ba;
  public static String[] bb;
  public static String[] bc;
  public static String bd;
  public static String be;
  public static String bf;
  public static String bg;
  public static String[] bh;
  public static String bi;
  public static String bj;
  public static String[] bk;
  public static String bl;
  public static String bm;
  private static int[] sk;
  public static String bn;
  public static String bo;
  public static String bp;
  public static String bq;
  public static String br;
  public static String bs;
  public static String bt;
  public static String[] bu;
  public static String bv;
  public static String bw;
  public static String[] bx;
  public static String by;
  public static String[] bz;
  public static String ca;
  public static String cb;
  public static String[] cc;
  public static String cd;
  public static String ce;
  public static String cf;
  public static String cg;
  public static String ch;
  public static String ci;
  public static String[] cj;
  public static String ck;
  public static String cl;
  public static String cm;
  public static String cn;
  public static String co;
  public static String cp;
  public static String cq;
  public static String cr;
  public static String cs;
  public static String ct;
  public static String[] cu;
  public static String[] cv;
  public static String cw;
  public static String cx;
  public static String cy;
  public static String cz;
  public static String da;
  public static String[] db;
  public static int dc;
  public static String[] dd;
  public static String de;
  public static String df;
  public static String dg;
  public static String dh;
  public static String[] di;
  public static String dj;
  public static String dk;
  public static String dl;
  public static String dm;
  public static String dn;
  public static String doa;
  public static String[] dp;
  public static String dq;
  public static String dr;
  public static String ds;
  public static String dt;
  public static String du;
  public static String[] dv;
  public static String dw;
  public static String dx;
  public static String dy;
  public static String dz;
  public static String ea;
  public static String[] eb;
  public static String ec;
  public static String ed;
  public static String ee;
  public static String[] ef;
  public static String[] eg;
  public static String eh;
  public static String ei;
  public static String ej;
  public static String ek;
  public static String el;
  public static String em;
  public static String[] en;
  public static String[] eo;
  public static String ep;
  public static String eq;
  public static String er;
  public static String es;
  public static String et;
  public static String eu;
  public static String ev;
  public static String ew;
  public static String ex;
  public static String ey;
  public static String ez;
  public static String fa;
  public static String fb;
  public static String[] fc;
  public static String fd;
  public static String[] fe;
  public static String ff;
  public static String fg;
  public static String fh;
  public static String fi;
  public static String fj;
  public static String[] fk;
  public static String fl;
  public static String fm;
  public static String fn;
  public static String fo;
  public static String[] fp;
  public static String fq;
  public static String fr;
  public static String[] fs;
  public static String ft;
  public static String[] fu;
  public static String fv;
  public static String fw;
  public static String fx;
  public static String fy;
  public static String fz;
  public static String ga;
  public static String gb;
  public static String gc;
  public static String gd;
  public static String ge;
  public static String gf;
  public static String gg;
  public static String gh;
  public static String gi;
  public static String[][] gj;
  public static String gk;
  public static String gl;
  public static String gm;
  public static String gn;
  public static String go;
  public static String gp;
  public static String gq;
  public static String gr;
  public static String gs;
  public static String gt;
  public static String gu;
  public static String[] gv;
  public static String gw;
  public static String gx;
  public static String gy;
  public static String gz;
  public static String ha;
  public static String hb;
  public static String hc;
  public static String hd;
  public static String he;
  public static String hf;
  public static String hg;
  public static String hh;
  public static String hi;
  public static String[] hj;
  public static String hk;
  public static String hl;
  public static String[] hm;
  public static String hn;
  public static String ho;
  public static String[] hp;
  public static String hq;
  public static String hr;
  public static String hs;
  public static String[] ht;
  public static String hu;
  public static String hv;
  public static String hw;
  public static String[] hx;
  public static String hy;
  public static String hz;
  public static String[] ia;
  public static String ib;
  public static String ic;
  public static String id;
  public static String ie;
  public static String ifa;
  public static String ig;
  public static String[] ih;
  public static String ii;
  public static String ij;
  public static String ik;
  public static String il;
  public static String[] im;
  public static String in;
  public static String io;
  public static String ip;
  public static String iq;
  public static String ir;
  public static String is;
  public static String it;
  public static String iu;
  public static String iv;
  public static String[] iw;
  public static String ix;
  public static String iy;
  public static String iz;
  public static String ja;
  public static String jb;
  public static String jc;
  public static String jd;
  public static String[][] je;
  public static String jf;
  public static String jg;
  public static String jh;
  public static String[] ji;
  public static String jj;
  public static String jk;
  public static String jl;
  public static String[] jm;
  public static String jn;
  public static String jo;
  public static String jp;
  public static String jq;
  public static String jr;
  public static String js;
  public static String jt;
  public static String ju;
  public static String jv;
  public static String jw;
  public static String jx;
  public static String jy;
  public static String jz;
  public static String ka;
  public static String kb;
  public static String kc;
  public static String kd;
  public static String[][] ke;
  public static String kf;
  public static String[] kg;
  public static String[] kh;
  public static String ki;
  public static String kj;
  public static String kk;
  public static String kl;
  public static String km;
  public static String kn;
  public static String ko;
  public static String kp;
  public static String[] kq;
  public static String kr;
  public static String ks;
  public static String kt;
  public static String ku;
  public static String[] kv;
  public static String kw;
  public static String kx;
  public static String ky;
  public static String[] kz;
  public int[] la = new int[sk[0]];
  public static String lb;
  public static String lc;
  public static String[] ld;
  public static String le;
  public static String[] lf;
  public static String lg;
  public static String[] lh;
  public static String li;
  public static String lj;
  public static String lk;
  public static String[] ll;
  public static String lm;
  public static String ln;
  public static String[] lo;
  public static String lp;
  public static String lq;
  public static String lr;
  public static String ls;
  public static String lt;
  public static String lu;
  public static String lv;
  public static String lw;
  public static String[] lx;
  public static String[] ly;
  public static String lz;
  public static String ma;
  public static String mb;
  public static String mc;
  public static String md;
  public static String[] me;
  public static String[] mf;
  public static String[] mg;
  public static String mh;
  public static String mi;
  public static String mj;
  public static String mk;
  public static String ml;
  public static String mm;
  public static String mn;
  public static String mo;
  public static String mp;
  public static String mq;
  public static String[] mr;
  public static String ms;
  public static String[] mt;
  public static String mu;
  public static String mv;
  public static String[] mw;
  public static String mx;
  public static String my;
  public static String mz;
  public static String na;
  public static String nb;
  public static String nc;
  public static String nd;
  public static String ne;
  public static String nf;
  public static String ng;
  public static String nh;
  public static String ni;
  public static String nj;
  public static String nk;
  public static String nl;
  public static String[] nm;
  public static String nn;
  public static String no;
  public static String np;
  public static String nq;
  public static String[] nr;
  public static String ns;
  public static String nt;
  public static String nu;
  public static String[] nv;
  public static String nw;
  public static String[] nx;
  public static String[] ny;
  public static String[] nz;
  public static String oa;
  public static String ob;
  public static String oc;
  public static String[] od;
  public static String[] oe;
  public static String of;
  public static String[] og;
  public static String oh;
  public static String oi;
  public static String oj;
  public static String ok;
  public static String ol;
  public static String om;
  public static String on;
  public static String oo;
  public static String op;
  public static String oq;
  public static String or;
  public static String os;
  public static String ot;
  public static String ou;
  public static String[] ov;
  public static String ow;
  public static String ox;
  public static String oy;
  public static String[] oz;
  public static String pa;
  public static String pb;
  public static String pc;
  public static String pd;
  public static String pe;
  public static String pf;
  public static String pg;
  public static String ph;
  public static String pi;
  public static String pj;
  public static String pk;
  public static String pl;
  public static String pm;
  public static String pn;
  public static String po;
  public static String pp;
  public static String pq;
  public static String[] pr;
  public static String ps;
  public static String pt;
  public static String pu;
  public static String pv;
  public static String[] pw;
  public static String px;
  public static String[] py;
  public static String pz;
  public static String qa;
  public static String qb;
  public static String[] qc;
  public static String qd;
  public static String qe;
  public static String[] qf;
  public static String qg;
  public static String qh;
  public static String qi;
  public static String qj;
  public static String qk;
  public static String ql;
  public static String qm;
  public static String qn;
  public static String[] qo;
  public static String qp;
  public static String[] qq;
  public static String qr;
  public static String qs;
  public static String qt;
  public static String qu;
  public static String[] qv;
  public static String qw;
  public static String qx;
  public static String[] qy;
  public static String qz;
  public static String ra;
  public static String[] rb;
  public static String rc;
  public static String[] rd;
  public static String re;
  public static String rf;
  public static String rg;
  public static String rh;
  public static String ri;
  public static String rj;
  public static String rk;
  public static String rl;
  public static String rm;
  public static String[] rn;
  public static String[] ro;
  public static String rp;
  public static String rq;
  public static String[] rr;
  public static String rs;
  public static String rt;
  public static String ru;
  public static String rv;
  public static String rw;
  public static String rx;
  public static String ry;
  public static String rz;
  public static String sa;
  public static String sb;
  public static String sc;
  public static String sd;
  public static String se;
  public static String[] sf;
  public static String sg;
  public static String sh;
  public static String si;
  public static String sj;
  
  private static boolean a(int paramInt1, int paramInt2)
  {
    return paramInt1 == paramInt2;
  }
  
  private static boolean a(int paramInt)
  {
    return paramInt == 0;
  }
  
  public static String a(String paramString1, String paramString2)
  {
    return cl.a(paramString1, "#", paramString2);
  }
  
  public static void a()
  {
    String str = a("hd.txt");
    fn.j().a("Hướng dẫn", str, sk[1]);
  }
  
  public static void b()
  {
    if (a(dc))
    {
      hu = "Viên ngọc này không thể gọt.";
      ry = "Viên ngọc đã đạt cấp độ tối đa.";
      nn = "Đăng ký một tài khoản sẽ giúp nhân vật đang chơi của bạn còn mãi. Bạn có muốn đăng ký không?";
      gw = "Nhiệm vụ bí ẩn";
      gt = "- Nâng hiếu chiến lên 1.";
      ns = "- Hoàn thành hang động 1 lần.";
      ig = "- Hoàn thành tà thú 1 lần.";
      gu = "- Hoàn thành 1 lần nâng cấp.";
      pm = "- Hoàn thành 10 nhiệm vụ hàng ngày.";
      km = "- Lấy 1000 điểm chiến trường.";
      co = "- Hoàn thành 1 lần thất thú ải.";
      cd = "- Hoàn thành 3 lần quay số.";
      { "Katana", "Bokken", "Shuriken", "Tessen", "Kunai" }[sk[6]] = "Liên Server";
      qj = "Tỉ lệ thắng";
      jw = "Bạn đã tham gia: ";
      am = "Số người tham gia: ";
      jj = "Vòng xoay may mắn";
      gp = "Tham gia";
      kb = "Tiếp tục";
      fw = "Tài khoản của bạn chưa được xác thực. Nếu bạn xóa trò chơi, hoặc đăng nhập tài khoản khác, nhân vật đang chơi của bạn sẽ mất vĩnh viễn.";
      fj = "Chơi mới";
      rq = "Chơi tiếp";
      fm = "Đổi tài khoản";
      ci = "Máy Chủ: ";
      br = "hạng";
      ew = "Thách Đấu";
      dh = "Thông tin";
      rr = new String[] { "Bạn có thể nhấn giữ nút chuyển mục tiêu để hiển thị danh sách người chơi khác trong map", "Đối với máy có bàn phím, bạn có thể gán phím tắt cho các phím 7,8,9 hoặc Q,W,E để sử dụng kỹ năng", "Cừu sát sẽ làm tăng 2 điểm hiếu chiến. Đồ sát sẽ làm tăng 1 điểm hiếu chiến", "Đối với Kiếm, Kunai, Đao: Nên tăng Sức Mạnh, Thể Lực, Thân pháp", "Đối với Cung, Phi Tiêu, Quạt: Nên tăng Chakra, Thể Lực, Thân pháp", "Lập tổ đội đi luyện cùng nhau bạn sẽ nhận được nhiều kinh nghiệm hơn và làm nhiệm vụ nhanh hơn", "Để giảm hiếu chiến, bạn phải bị người khác đánh trọng thương. Vào đấu trường để thi đấu để giảm", "Khi tách đá khỏi trang bị, bạn sẽ thu lại một nửa số đá ép vào lúc đầu", "Bạn có thể đổi Xu từ Yên, với điều kiện có đủ điểm hoạt động", "Bạn sẽ có phần thưởng nếu đạt thành tích cao nhất trong đấu trường mỗi ngày", "Để vào khu vực đấu trường, hãy tìm Rikudou đứng ở mỗi trường", "Bạn có thể tăng tỉ lệ thành công khi nâng cấp đồ bằng cách chọn phương pháp Cẩn Thận, nhưng sẽ tốn Lượng", "Bạn được tặng 10 lượng khi đạt cấp độ 20 tại NPC Okanechan", "Tiền Lượng được chia sẻ cho 3 nhân vật trong 1 tài khoản" };
      pa = "Quy định";
      ki = "Xin chờ..";
      gs = "Chờ";
      lu = "Menu";
      lc = "Cần";
      gd = "Di chuyển tới";
      rm = "Ngôn ngữ";
      cp = "Xóa bộ nhớ tạm";
      nx = new String[] { "Tiếng việt", "English" };
      { "ភាសាខ្មែរ" }[sk[3]] = "ភាសាអង់គ្លេស";
      pc = "Bạn có muốn thoát game để chọn lại ngôn ngữ không ?";
      qt = "Đóng";
      dk = "Ẩn";
      kn = "Tự đánh";
      cw = "Đứng yên";
      ad = "do";
      dx = "Khóa";
      ku = "Mở khóa";
      oc = "Số seri";
      rl = "Mã thẻ";
      gm = "Bật";
      d = "Tắt";
      ax = "Mở link";
      rw = "Nạp";
      pp = "Kích hoạt";
      v = "Cấu hình";
      ng = "Xóa";
      kl = "Xem";
      oj = "Tiếp tục";
      ic = "Mã rương";
      dj = "Thẻ cào";
      ik = "Tiếp";
      js = "Sử dụng";
      nk = "Sắp xếp";
      fb = "Bỏ ra đất";
      bj = "Tách";
      cz = "Trang bị đã được tách, bạn nhận được ";
      nt = "Có";
      jv = "Lấy ra";
      lt = "Bỏ ra";
      ga = "Rút xu";
      rg = "Cất xu";
      cm = "Chuyển xu";
      bv = "Cất vào";
      kj = "Bán";
      dz = "Bán nhiều";
      ok = "Bán hết";
      dn = "Giá";
      hn = "Mua";
      kx = "Mua nhiều";
      mm = "Không";
      bs = "Thoát";
      g = "Chat";
      nd = "OK";
      ou = "Tài khoản";
      jp = "Mật khẩu";
      gx = "Nhập lại";
      pl = "TK";
      lb = "MK";
      eh = "lại";
      ey = "Xin khởi động lại game.";
      hs = "Nhập lại mật khẩu";
      ce = "Nhớ";
      iu = "Bỏ";
      cl = "Đăng ký";
      mq = "Tăng đồ họa (cho máy mạnh)";
      kk = "Giảm đồ họa (cho máy yếu)";
      jl = "Bạn chưa nhập tên tài khoản";
      by = "Tài khoản không được có ký tự đặt biệt.";
      gi = "Bạn chưa nhập mật khẩu lần một.";
      oy = "Bạn chưa nhập mật khẩu lần hai.";
      mn = "Tên tài khoản phải nhiều hơn 5 ký tự";
      jd = "Mật khẩu không chính xác.";
      og = new String[] { "Để xác thực với tên", "bạn phải đồng ý với quy định của trò chơi." };
      jh = "Bạn đang sử dụng mạng gì? (Bạn có thể chọn lại từ Menu)";
      dq = "Có phải bạn dùng số điện thoại đăng ký không ?";
      aw = "tin nhắn riêng";
      fu = new String[] { "Tin nhắn gia tộc, nhóm", "Tin nhắn gia tộc", "Tin nhắn nhóm" };
      dl = "hộ tống";
      re = "Cộng";
      jq = "Cộng nhiều";
      rx = "điểm tiềm năng";
      o = "Đồng ý";
      gk = "Hủy";
      oa = "Danh sách";
      nf = "Thời gian";
      ab = "Thành tích";
      gq = "Tối đa";
      rv = "Tích lũy";
      ls = "Đang kết nối";
      nb = "Đang đăng ký";
      df = "Đang đăng nhập";
      pb = "Chưa hoàn thành";
      ri = "Thời gian hoàn thành";
      ow = "Tinh thần đồng đội";
      jt = "Chọn";
      iy = "Bỏ chọn";
      mv = "Chọn vật phẩm để xem thông tin.";
      os = "Gán";
      nl = "Kết quả";
      y = "Đánh giá";
      f = "Cấp";
      ib = "cấp";
      mz = "Bạn có muốn thoát không?";
      qh = "Nhân vật cần đổi tên";
      bt = "Máy chủ này đang bảo trì hoặc quá tải. Vui lòng thử lại sau hoặc chọn máy chủ khác.";
      qu = "Tạo mới";
      dw = "Tên nhân vật";
      pi = "Tên nhân vật muốn kết bạn";
      mo = "đã trở thành hảo hữu.";
      ep = "Đang tải... ";
      doa = "Đóng";
      qg = "Nhận thưởng";
      oq = "rương hang động";
      ez = "Hành trang đã được mở rộng";
      ot = "Khoảng cách hộ tống quá xa, nhiệm vụ đã thất bại";
      rp = "Người được hộ tống đã trọng thương, nhiệm vụ đã thất bại";
      ph = "vĩnh viễn";
      pd = "Chưa nâng cấp";
      ba = "Không thể nâng cấp";
      ej = "Dùng vật phẩm đặc biệt để nâng cấp";
      bd = "Luyện";
      cs = "Luyện đá thành công, bạn nhận được";
      bh = new String[] { "Chỉ được chuyển hóa trang bị cùng", "loại và cùng cấp trở lên.", "Sẽ khóa trang bị sau khi chuyển hóa." };
      io = "thất bại, bạn nhận được";
      mh = "Đã gửi tin nhắn, xin chờ tin nhắn xác nhận.";
      ho = "Không thể gởi tin nhắn. Xin kiểm tra tiền và thử khởi động lại game.";
      gb = "Xu đang gửi";
      rj = "Bắt đầu";
      ja = "Chọn 2 viên đá trở lên";
      ms = "Chọn Trang Bị cần tách Đá";
      md = "Chọn Vật Phẩm và Xu trao đổi";
      no = "Sang Hành Trang để chọn";
      sb = "Đổi";
      ck = "ô";
      sj = "ô thứ";
      im = new String[] { "Phím Q", "Phím W", "Phím E" };
      fe = new String[] { "Phím 7", "Phím 8", "Phím 9" };
      ke = new String[][] { { "ngắn", "cài trâm", "búi", "xù" }, { "đeo băng", "bó xù", "samurai", "nhím" } };
      qy = new String[] { "Hành trang", "Kỹ năng", "Tiềm năng", "Thông tin", "Trang bị", "Thú Cưỡi" };
      di = new String[] { "Tiệm Y Phục", "Hành trang" };
      b = new String[] { "Nón", "Hành trang" };
      kz = new String[] { "Áo", "Hành trang" };
      ag = new String[] { "Găng tay", "Hành trang" };
      hx = new String[] { "Quần", "Hành trang" };
      eg = new String[] { "Giày", "Hành trang" };
      rb = new String[] { "Dây chuyền", "Hành trang" };
      qf = new String[] { "Nhẫn", "Hành trang" };
      fc = new String[] { "Ngọc bội", "Hành trang" };
      lo = new String[] { "Bùa", "Hành trang" };
      lh = new String[] { "Binh khí", "Hành trang" };
      nv = new String[] { "Dược phẩm", "Hành trang" };
      ac = new String[] { "Dược phẩm", "Hành trang" };
      pr = new String[] { "Thức ăn", "Hành trang" };
      bx = new String[] { "Thức ăn", "Hành trang" };
      rd = new String[] { "Nâng cấp", "Hành trang" };
      mt = new String[] { "Gian hàng", "Hành trang" };
      dd = new String[] { "Chuyển hóa", "Hành trang" };
      a = new String[] { "Luyện đá", "Hành trang" };
      ll = new String[] { "Rương đồ", "Hành trang" };
      cc = new String[] { "Cửa hàng", "Quầy sách", "Thời trang", "Gia Tộc" };
      py = new String[] { "Bảo vật" };
      cv = new String[] { "Tách Đá", "Hành trang" };
      ih = new String[] { "Giao dịch", "Hành trang" };
      qc = new String[] { "Luyện thạch", "Hành trang" };
      nz = new String[] { "Dịch chuyển", "Hành trang" };
      nr = new String[] { "Tinh luyện", "Hành trang" };
      jm = new String[] { "Khảm ngọc", "Hành trang" };
      kh = new String[] { "Luyện ngọc", "Hành trang" };
      hj = new String[] { "Gọt ngọc", "Hành trang" };
      dp = new String[] { "Giao đồ", "Hành trang" };
      kg = new String[] { "Tháo ngọc", "Hành trang" };
      ia = new String[] { "Nhặt đồ", "Hành trang" };
      { "Del đồ" }[sk[3]] = "Hành trang";
      hc = "Xóa";
      ah = "Thêm";
      fy = "Ta sẽ làm giảm đi chỉ số bất lợi trên viên ngọc này.";
      ie = "Ta sẽ giúp ngươi tháo bỏ ngọc khảm trên trang bị.";
      lf = new String[] { "- Sử dụng Yên, nếu không đủ dùng Xu", "- Qua trang Hành Trang để chọn Đá", "- Số lượng đá từ 2 đến 24" };
      eb = new String[] { "- Sử dụng Yên, nếu không đủ dùng Xu", "- Nâng cấp cẩn thận cần dùng lượng", "- Chỉ chọn Trang Bị và Đá", "Trang bị đã được nâng cấp tối đa" };
      fk = new String[] { "- Sử dụng Yên, nếu không đủ dùng Xu", "- Chỉ chọn Trang Bị và Ngọc" };
      da = "Khóa G.Dịch";
      lr = "- Luyện thành Đá cấp";
      is = "- Cần: # yên";
      bf = "- Cần: # lượng";
      rz = "- Cần: # xu";
      eq = "- Xác xuất thành công";
      lg = "(thành công ";
      qn = "Cộng";
      it = "Đã khóa";
      ec = "Tiêu diệt";
      lq = "Bắt tà thú";
      kw = "Tiêu diệt tinh anh";
      iq = "Tiêu diệt thủ lĩnh";
      ft = "Hộ tống trẻ lạc";
      cx = "Không khóa";
      nj = "Hạn sử dụng";
      ir = "Giá bán: # yên";
      eu = "Giá mua: # xu";
      ee = "Giá mua: # xu gia tộc";
      qx = "Giá mua: # yên";
      ml = "Giá mua: # lượng";
      om = "lượng";
      c = "Chưa có";
      du = "Cấp kế: cấp #";
      jz = "Cấp hiện tại: cấp #";
      lj = "Cấp tối đa";
      nh = "Đã đạt cấp độ tối đa";
      he = "Yêu cầu: trình độ cấp";
      gz = "Lớp: ";
      gv = new String[] { "Chính tuyến", "Phụ tuyến" };
      et = "Nhiệm vụ";
      sd = "Nhận NV ở";
      bn = "Bạch giả";
      ol = "Hắc giả";
      mu = "Trung lập";
      px = "Nhóm";
      q = "Tìm Nhóm";
      my = "Điểm hiếu chiến của bạn hiện tại là ";
      cu = new String[] { "Bạn bè", "Thù Địch" };
      hf = "Bạn chưa kết bạn với ai";
      ma = "chờ xác nhận";
      gc = "đã thêm bạn vào danh sách bạn bè";
      ifa = "Bạn đã thêm";
      hr = "vào danh sách";
      gh = "Bạn và";
      rn = new String[] { "Cửa hàng", "Bản thân", "Bản đồ", "Tổng hợp", "Thoát", "Trang sức", "Tính năng", "Dược khóa", "Dược phẩm", "Tạp hóa khóa", "Tạp hóa", "Cường hóa", "Luyện hóa", "Luyện hóa khóa", "Thủ khố", "Tách trang bị", "Khu vực", "Giao dịch", "Tin nhắn", "Chọn Nhân vật" };
      iw = new String[] { "Hỗ trợ bị động", "Chủ động sử dụng", "Chủ động sử dụng", "Chủ động sử dụng", "Chủ động sử dụng" };
      bu = new String[] { "Nhân vật: ", "Hiếu chiến: ", "Trình độ: ", "Lớp: ", "", "HP: ", "MP: ", "Tốc độ: ", "Tấn công: ", "Hỏa chống: ", "Băng chống: ", "Phong chống: ", "Giảm sát thương: ", "Độ chính xác: ", "Khả năng né đòn: ", "Chí mạng: ", "Phản đòn cận chiến: ", "Cường khắc: ", "Hạ khắc: ", "Điểm hoạt động: " };
      qs = " lần";
      kv = new String[] { "Học Giả", "Hạ nhẫn", "Trung Nhẫn", "Thượng Nhẫn", "Nhẫn Giả" };
      ro = new String[] { "Điểm hoạt động: ", "Danh vọng vũ khí: ", "Danh vọng dây chuyền: ", "Danh vọng nhẫn: ", "Danh vọng ngọc bội: ", "Danh vọng bùa: ", "Danh vọng nón: ", "Danh vọng áo: ", "Danh vọng găng tay: ", "Danh vọng quần: ", "Danh vọng giày: ", "Hoàn thành NV mỗi ngày: ", "Truy bắt Tà Thú còn: ", "Học sách tiềm năng sơ: ", "Học sách kỹ năng sơ: ", "Gia tộc: ", "Vào hang động còn: ", "Điểm tinh tú: ", "Số lần ăn bánh phong lôi: ", "Số lần ăn bánh băng hỏa: " };
      au = new String[] { "Tên: ", "Giới tính: ", "Tóc: " };
      me = new String[] { "Nữ", "Nam" };
      bz = new String[] { "Sức mạnh", "Thân pháp", "Thể lực", "Chakra" };
      jc = "Chưa có ai cừu sát bạn";
      oh = "Bạn đã thắng #.";
      mi = "Bạn đã thua #.";
      al = "Cuộc so tài giữa bạn và # đã kết thúc";
      lx = new String[] { "", "Tinh Anh", "Thủ Lĩnh", "Tà Thú" };
      ev = " bắt đầu cừu sát bạn";
      hy = "Điểm tiềm năng";
      er = "Điểm kỹ năng";
      ay = "Không đủ MP để sử dụng";
      rf = "Chỉ được vật phẩm không khóa";
      cq = "Chỉ được chọn vật phẩm không khóa và không có hạn sử dụng";
      ps = "Chỉ được chọn Đá để luyện cấp";
      oo = "Chỉ được chọn Đá, Trang bị, và Bảo hiểm để nâng cấp";
      lp = "Chỉ được chọn Trang bị và vật phẩm Hoán chuyển.";
      ko = "Trang bị không thể nâng cấp";
      jx = "Trang bị đã nâng cấp tối đa";
      cr = "Chỉ được chọn trang bị đã nâng cấp mới có thể tách được";
      rh = "Vật phẩm giao dịch đã đầy";
      ky = "Số lượng đã đầy";
      se = "Bạn không đủ điểm cộng";
      cb = "Bạn chưa nhập điểm cộng";
      hi = "Bạn chưa nhập thông tin loại thẻ";
      in = "Bạn chưa nhập thông tin mệnh giá.";
      ff = "Bạn chưa nhập thông tin số seri";
      lm = "Bạn chưa nhập thông tin khoảng thời gian nạp.";
      dt = "Bạn chưa nhập vào tên cần thêm";
      iz = "Nhập điểm";
      ct = "Nhập Xu";
      ed = "Nhập số lượng";
      fv = "Tên tài khoản";
      qm = "Xu";
      kf = "Yên";
      ru = "Lượng";
      n = "Cất vào hành trang";
      hq = "Bạn có thật sự muốn bãi nhiệm chức vụ của người này không?";
      fn = "Trục xuất thành viên sẽ bị giảm ngân sách gia tộc (xem chi tiết tại Npc Kanata). Bạn có thật sự muốn trục xuất người này không?";
      sa = "Tự rời khỏi gia tộc sẽ bị giảm xu trong hành trang (xem chi tiết tại Npc Kanata). Bạn có muốn rời khỏi không?";
      bq = "Sau khi sử dụng vật phẩm sẽ bị khóa. Bạn có muốn sử dụng không?";
      fd = "Sau khi bán vật phẩm sẽ không thể phục hồi. Bạn có muốn bán vật phẩm này không?";
      ak = new String[][] { { "nón" }, { "vũ", "khí" }, { "áo" }, { "vòng", "cổ" }, { "găng", "tay" }, { "nhẫn" }, { "quần" }, { "bội" }, { "giày" }, { "bùa" }, { "thú", "nuôi" }, { "mặt", "nạ" }, { "ninja", "yoroi" }, { "gia", "tộc" }, { "chưa", "mở" }, { "bí", "kíp" }, { "áo", "giáp" }, { "yên", "" }, { "cương", "" }, { "trang", "sức" }, { "động", "cơ" }, { "định", "vị" }, { "bộ", "đk" }, { "bình", "nitro" } };
      mg = new String[] { "Chưa vào trường", "Trường: Hirosaki", "Trường: Ookaza", "Trường: Haruna" };
      oe = new String[] { "", "Thuộc tính: Hỏa", "Thuộc tính: Thủy", "Thuộc tính: Phong", "", "", "" };
      bp = "Bạn nhận được";
      ox = "Bạn chưa nhập vào số lương";
      ao = "Không thể bán trang bị đã nâng cấp";
      af = "Bạn không đủ xu để chuyển.";
      nu = "Bạn không đủ xu để cất";
      mp = "Bạn không đủ xu để rút";
      gn = "Bạn không đủ số lượng để bán";
      qo = new String[] { "Thành công, trang bị được lên cấp ", "Thất bại, trang bị trở về cấp ", "Trang bị được nâng cấp tối đa", "Trang bị cấp" };
      ld = new String[] { "Khảm ngọc thành công", "Khảm ngọc thất bại" };
      kp = "tháng";
      ex = "tuần";
      jn = "ngày";
      ei = "giờ";
      dm = "giây";
      qk = "phút";
      iv = "Ảnh hưởng";
      qa = "Phạm vi";
      na = "MP mất";
      ap = "Khoảng cách thi triển";
      nw = "Phải có từ 2 viên đá trở lên mới có thể luyện được";
      qd = "Giới tính không phù hợp";
      sg = "Không có người chơi khác";
      cf = "Trình độ của bạn chưa đạt yêu cầu";
      fz = "Đá đã đạt cấp độ tối đa";
      ca = "Đá sau khi luyện cấp sẽ bị khóa. Bạn có muốn tiếp tục không?";
      fl = "Bạn không đủ xu để luyện đá";
      hb = "Bạn không đủ lượng để nâng cấp trang bị";
      ai = "Bạn không đủ xu hoặc yên để nâng cấp trang bị";
      dr = "Nhiều đá quá sẽ bị lãng phí. Bạn có chắc chắn muốn nâng cấp?";
      kd = "Sau khi nâng cấp trang bị sẽ bị khóa. Bạn có muốn tiếp tục không?";
      aj = "Không thể tách trang bị chưa nâng cấp";
      ip = "Hành trang không đủ chỗ trống";
      gr = "Bạn có thật sự muốn tách không?";
      ka = "Bạn có thật sự muốn chuyển hóa không?";
      li = "mời bạn giao dịch. Bạn có muốn giao dịch không?";
      bm = "mời bạn vào tộc. Bạn có muốn là thành viên của gia tộc '#' không?";
      dg = "muốn xin vào gia tộc. Bạn có đồng ý không?";
      ij = "muốn tỷ thí với bạn. Bạn có đồng ý không?";
      gl = "mời bạn vào nhóm. Bạn có muốn vào không?";
      cn = "muốn xin vào nhóm. Bạn có đồng ý không?";
      ix = "Chuyển hóa trang bị thành công.";
      mr = new String[] { "Giới tính: nữ", "Giới tính: nam" };
      ni = "Khu vực";
      fx = "Dân số";
      po = "Nhóm";
      np = "Hiện tại bạn không vào nhóm nào";
      bl = "lần";
      hm = new String[] { "Thông tin", "Thành viên", "Nhà Kho", "Thống Kê", "Thần Thú" };
      ly = new String[] { "Gia tộc: ", "Tộc trưởng: ", "Thành viên: ", "Cấp: ", "Kinh nghiệm: ", "Ngân sách: ", "Thành lập: ", "Cống hiến: ", "Phí duy trì: ", "Phí nâng cấp: ", "Vào Lãnh Địa Gia Tộc: còn ", "Cống hiến tuần: ", "Sử dụng lệnh bài còn: " };
      oz = new String[] { "xu lúc", "Thành lập gia tộc, ngân sách nhận", "bị trục xuất, ngân sách trừ", "đóng góp quỹ gia tộc, ngân sách tăng", "rút quỹ gia tộc, ngân sách giảm", "Thu phí duy trì gia tộc, ngân sách giảm", "nâng cấp gia tộc, ngân sách giảm" };
      ju = "Hiện tại bạn chưa gia nhập gia tộc";
      fh = "Phát cho Thành viên";
      gj = new String[][] { { "Trường Hirosaki" }, { "Trường Haruna" }, { "Trường Ookaza" }, { "Làng", "Làng Kojin", "Làng Sanzu", "Làng Tone", "Làng chài", "Làng Chakumi", "Làng Echigo", "Làng Oshin" }, { "Khu vực" } };
      eo = new String[] { "Nón", "Nhân", "Áo", "Dây chuyền", "Găng tay", "Nhẫn", "Quần", "Ngọc bội", "Giày", "Bùa" };
      bb = new String[] { "Kích ẩn", "Kích cấp độ" };
      ht = new String[] { "", "Hỏa", "Thủy", "Phong" };
      fs = new String[] { "Nhân vật", "Level", "" };
      ea = "Vô chiêu thắng hữu chiêu. Hiện tại bạn chưa có chiêu để đánh.";
      r = "Bạn chưa có vũ khí. Xin vào Menu/Bản Thân/Trang bị để kiểm tra";
      jf = "Vật phẩm đã bị khóa";
      ar = "Vật phẩm, trang bị và đá";
      lv = "Mức giá (xu)";
      hv = "Mức giá (yên)";
      ln = "Đã hết hiệu quả thức ăn";
      l = "Level của bạn không đủ để sử dụng";
      nq = "Đã hết bình MP";
      mk = "Đã hết bình HP";
      j = new String[] { "Giao dịch", "Tỷ thí", "Cừu sát", "Kết bạn", "Mời vào nhóm", "Phục hồi", "Xem thông tin", "Chat riêng", "Mời vào tộc", "Xin vào tộc", "Chặn xin vào tộc", "Tự Hồi Sinh", "Cấm Chat" };
      qe = "Bạn đang ở khu vực này";
      ef = new String[] { "Hãy đi tìm ", " ở ", " để nhận nhiệm vụ.", "Bạn đã hoàn thành hết nhiệm vụ phiên bản này, vui lòng chờ cho đến khi ra phiên bản tiếp theo." };
      od = new String[] { "Kiệt sức", "Đứng nhìn", "Quay về", "Hồi sinh tại chỗ (1 lượng)" };
      rs = "Sau khi gia nhập vào lớp học, thì có thể nhận nhiệm vụ từ hiệu trưởng";
      bo = "Tạo nhóm";
      fo = "Rời nhóm";
      ch = "Nhóm trưởng";
      t = "Khóa nhóm";
      of = "Mở nhóm";
      qr = "Xin gia nhập";
      id = "Tìm lại";
      il = "Hiện tại bạn chưa có nhóm";
      kr = "Chưa có thông tin";
      at = "Hiện tại không tìm thấy nhóm";
      sf = new String[] { "PK Thường", "PK Phe", "PK Bang", "PK Đồ Sát" };
      qv = new String[] { "Trạng thái PK", "Bạn bè", "Thù Địch", "Nhóm", "Tìm nhóm", "Gia tộc", "Bảo vệ tài khoản", "Tự động", "Bán Shinwa", "Luyện thạch", "Tinh luyện", "Dịch chuyển" };
      dv = new String[] { "Bản đồ", "Nhiệm vụ", "Gia tộc" };
      aa = new String[] { "Tộc trưởng", "Tộc phó", "Trưởng lão", "Ưu tú", "Thành viên" };
      bc = new String[] { "(TT)", "(TP)", "(TL)", "(UT)" };
      kq = new String[] { "Chỉ hiện Online", "Rời khỏi", "Thông báo", "Đóng góp", "Rút quỹ", "Nâng Cấp", "Mời vào lãnh địa", "Mời vào Gia tộc chiến", "Khai mở" };
      fi = "SX theo C.Hiến tuần";
      qq = new String[] { "Trục xuất", "Nhường", "Kết bạn" };
      si = " được lên làm nhóm trưởng.";
      jk = "Bạn bị đuổi ra khỏi nhóm";
      ql = "Mời vào nhóm";
      go = "Thêm";
      av = "Vũ khí không thích hợp.";
      ds = "Bạn có muốn xóa người này ra khỏi danh sách?";
      pw = new String[] { "Bạn phải vào trường để tăng điểm" };
      mf = new String[] { "Sức mạnh = Tấn công", "Thân pháp = né,chính xác", "Thể lực = HP", "Chakra = MP" };
      db = new String[] { "Không cần tăng sức mạnh", "Thân pháp = né,chính xác", "Thể lực = HP", "Chakra = Tấn công, MP" };
      op = "Đóng tab hiện tại";
      ov = new String[] { "Công cộng", "Bạn có thể chat với người đứng gần tại đây" };
      fp = new String[] { "Chung nhóm", "Bạn có thể chat với người trong cùng nhóm tại đây" };
      cj = new String[] { "Kênh thế giới", "Bạn mất 5 lượng mỗi lần chat kênh thế giới.", "Tất cả người đang online đều thấy bạn chat.", "Bạn sẽ bị khóa tài khoản nếu chửi bậy, quảng cáo wap web trên kênh thế giới." };
      en = new String[] { "Gia tộc", "Bạn có thể chat với người trong gia tộc tại đây" };
      em = "Chặn kênh thế giới: ";
      jb = "Chặn chat riêng: ";
      ae = "Bổ nhiệm";
      nc = "Bãi nhiệm";
      ra = "Trục xuất";
      hw = "Mật khẩu phải có độ dài là 6 ký tự.";
      mj = "Mật khẩu bảo vệ chỉ cho nhập số.";
      k = "Mật khẩu bảo vệ không được chứa số 0 ở đầu.";
      jr = "Mật khẩu bảo vệ chưa đúng.";
      aq = "Để sử dụng chức năng này bạn phải có Vạn biến lệnh.";
      gf = "Kích hoạt chức năng này phải tốn 10.000 yên. Bạn có muốn kích hoạt không ?";
      rt = "Nhập mật khẩu bảo vệ";
      sh = "Nhập số điện thoại đăng ký";
      mc = "Bạn chưa nhập số điện thoại đăng ký.";
      jg = "Để lấy mật khẩu cho '#'. Bạn phải sử dụng số điện thoại đăng ký cho tài khoản này.";
      u = "Đổi mật khẩu";
      cg = "Huỷ bảo vệ";
      fq = "Mật khẩu cũ";
      lk = "Mật khẩu mới";
      cy = "Bạn học được ";
      ks = "Nhập thông báo";
      pk = "Nhập số xu cần rút";
      pj = "Nhập số xu đóng góp cho gia tộc";
      lw = "Nhập thông tin loại thẻ và mệnh giá";
      fr = "Nhập thông tin số seri và khoảng thời gian nạp";
      az = "Nhập số lượng tách";
      kt = "Mệnh giá";
      sc = "Loại thẻ";
      qi = "Số seri";
      pz = "Thời gian nạp";
      fg = "Chặn tin nhắn";
      mx = "Báo lỗi với Admin";
      an = new String[] { "Gán phím tắt", "Gán vào 5 ô đánh" };
      gg = "Gửi tin nhắn thành công";
      kc = "Chúc mừng bạn đã gởi tin nhắn dự đoán thành công.";
      es = "Không thể gửi tin nhắn";
      be = "Tin nhắn gửi không thành công.";
      pg = "Không đủ xu để đóng góp";
      hd = "Số lượng tách không hợp lệ.";
      fa = "Giá trị nhập không hợp lệ.";
      qw = "Bạn có muốn hủy chức năng bảo vệ tài khoản không ?";
      hg = "muốn thách đấu với bạn ở lôi đài. Bạn có đồng ý không?";
      pe = "Sắp xếp theo giá";
      pq = "Sắp xếp theo cấp";
      s = "Sắp xếp theo tên";
      p = "Vật phẩm đã được gởi bán vào gian hàng";
      ne = "Mức phí cho mỗi lần bán là 5.000 xu";
      ii = "Bạn có muốn bán vật phẩm với giá # xu không ?";
      qp = "Bạn có muốn mua vật phẩm với giá # xu không ?";
      rk = "Người bán";
      gy = "còn";
      jo = "gần";
      ha = "hết giờ";
      nm = new String[] { "Đá", "Nón", "Vũ khí", "Áo", "Dây chuyền", "Găng tay", "Nhẫn", "Quần", "Ngọc bội", "Giày", "Bùa", "Linh tinh" };
      hl = " Vật phẩm bán được chịu thuế là 1%";
      ge = "Kinh nghiệm";
      or = "Thông báo Server";
      oi = "Giới thiệu bạn bè";
      on = "Lật hình";
      rc = "Số lượt lật còn lại của bạn là: ";
      ob = "muốn thách đấu với bạn và cả gia tộc. Bạn có đồng ý không?";
      hh = "Max options";
      w = "Mời người này";
      pf = "Mời tất cả";
      el = "'#' mời bạn vào gia tộc chiến. Bạn có muốn vào không?";
      i = "Nhập tên thành viên";
      je = new String[][] { { "Yêu cầu: gia tộc đạt cấp 5.", "Phí khai mở: 1.000.000 xu gia tộc." }, { "Yêu cầu: gia tộc đạt cấp 10.", "Phí khai mở: 5.000.000 xu gia tộc." }, { "Yêu cầu: gia tộc đạt cấp 15.", "Phí khai mở: 10.000.000 xu gia tộc." }, { "Yêu cầu: gia tộc đạt cấp 20.", "Phí khai mở: 20.000.000 xu gia tộc." }, { "Yêu cầu: gia tộc đạt cấp 25.", "Phí khai mở: 30.000.000 xu gia tộc." } };
      mw = new String[] { "Dùng HP khi còn dưới: ", "Dùng MP khi còn dưới:", "Dùng thức ăn cấp: ", "Dùng chiêu hổ trợ", "Dùng khiên mana", "Dùng đốt quái & ẩn thân", "Dùng phân thân", "Nhặt yên", "Nhặt HP, MP", "Nhặt N.Liệu(Đá)", "Luyện đá Max", "Nhặt Trang Bị", "Nhặt Trang Bị Lạ", "Nhặt VP Nhiệm Vụ", "Nhặt VP Sự Kiện", "Nhặt All", "Nhặt SVC", "Không nhặt gì cả", "Auto TTT", "AutoTTC", "ReMap", "Tàn sát map trống", "Auto Mua Thức Ăn", "TS khi hết MP", "Auto Reconnect", "Chuyển Map Hết Boss", "Săn TATL", "Đánh Quái Thường", "Đánh Tinh Anh", "Đánh Thủ Lĩnh", "Cộng tiềm năng", "Cộng kĩ năng", "Đánh theo nhóm", "Né PK", "Dùng Cổ Lệnh", "Mua Cổ Lệnh" };
      lz = "Dùng phím < và > để đổi giá trị";
      de = "Chạm vào ô thông số để đổi giá trị";
      mb = "Khoảng cách quá xa, không thể phục hồi cho người khác được";
      ek = "     Nhập giá trị phần trăm thấp tối thiểu            (Từ 10 đến 90)";
      hp = new String[] { "Cấp 1", "Cấp 10", "Cấp 20", "Cấp 30", "Cấp 40", "Cấp 50", "Cấp 60", "Cấp 70" };
      bk = new String[] { "Cấp 1", "Cấp 2", "Cấp 3", "Cấp 4", "Cấp 5", "Cấp 6", "Cấp 7", "Cấp 8", "Cấp 9", "Cấp 10", "Cấp 11", "Cấp 12" };
      hk = "Tài khoản đang được bảo vệ, vui lòng mở khóa.";
      qb = "Sinh lực";
      pv = "Tên thú cưỡi";
      ji = new String[] { "Luyện thạch cấp cao hơn bằng cách", "dùng 9 thạch cùng loại hoặc 3 thạch sơ", "và đá 11 hoặc 3 thạch trung và đá 12." };
      x = "Chỉ được chọn Tử tinh thạch sơ và trung cấp";
      bg = "Chỉ được chọn Đá và Tử tinh thạch để luyện";
      pt = "Chỉ cần dùng 1 viên đá để luyện";
      dy = "Cần kết hợp 3 Tử tinh thạch (trung) và đá 12 hoặc 3 tử tinh thạch (sơ) đá 11";
      as = "Chỉ được chọn đá cấp 11 trở lên";
      z = "Chỉ được chọn Tử thiên thạch cùng loại";
      bi = "Phải có từ 3 Tử tinh thạch trở lên mới có thể luyện được";
      m = "Số lượng Tử tinh thạch quá nhiều";
      pu = "Vật phẩm này không thể tinh luyện";
      bw = "Cần phải có đủ 20 chuyển tinh thạch để dịch chuyển trang bi";
      qz = "Vật phẩm này không dùng trong dịch chuyển";
      pn = "Cất kẹo";
      h = "Độ tinh luyện";
      jy = "Động cơ";
      le = "Nhiên liệu";
      hz = "Cho kẹo";
      ny = new String[] { "tử tinh", "tử tinh thạch sơ", "tử tinh thạch trung", "tử tinh thạch cao" };
      e = "Vật phẩm đã tinh luyện đến mức tối đa";
      return;
    }
    if (a(dc, sk[3]))
    {
      hu = "This gem can't roasting.";
      ry = "This gem reached max level.";
      nn = "Register account to keep your character safe. Do you want to register?";
      gw = "Hidden quest";
      gt = "- Get 1 aggressive point.";
      ns = "- Complete the cave of near school yard 1 times.";
      ig = "- Complete hunting wild beast 1 times.";
      gu = "- Upgrade equipment successful 1 times.";
      pm = "- Complete daily quest 10 times.";
      km = "- Get 1000 battlefield points.";
      co = "- Complete seven beasts gate 1 times.";
      cd = "- Enjoy lucky card 3 times.";
      { "Katana", "Bokken", "Shuriken", "Tessen", "Kunai" }[sk[6]] = "General Server";
      qj = "Win rate";
      jw = "Your coin: ";
      am = "Players: ";
      jj = "Lucky draw";
      gp = "Join now";
      kb = "Continue";
      fw = "Your account has not been verified. If you delete the game, or log another account, your character will lose playing forever.";
      fj = "New Play";
      rq = "Play";
      fm = "Change Username";
      ci = "Server: ";
      br = "rank";
      ew = "Challenge";
      dh = "Info";
      rr = new String[] { "Press change focus button to show all players on map", "For keyboard phones, assign shortcut keys 7,8,9 (or Q,W,E) to use skills.", "Berserk mode adds +2 agressive points.  Kill adds +1 agressive", "Sword, Kunai,and Blade increases Strength, Constitution, Dexterity", "Bow, Shuriken and Fan increases Chakra, Constitution, Dexterity", "Training as a team will earn experience and complete tasks faster", "Fighing other players on the battlefield will decrease combative points.", "When separated from the stone equipped, you will collect half amount of stone at the beginning.", "If you have enough action points, you can exchange coins from kin.", "The highest daily achievement in the arena will earn a reward.", "Find Rikudou to get into the arena.", "Precautionary measures cost money but will Increase the success rate of upgrading items", "When you reach Level 20, find Okanechan to received 10 gold bars.", "Gold bars will be split to 3 characters in 1 account" };
      pa = "Term";
      ki = "Xin chờ..";
      gs = "Wait";
      lu = "Menu";
      lc = "Need";
      gd = "Move to";
      rm = "Language";
      cp = "Clear cache";
      nx = new String[] { "Tiếng việt", "English" };
      { "ភាសាខ្មែរ" }[sk[3]] = "ភាសាអង់គ្លេស";
      pc = "Exit game to change the language ?";
      qt = "Close";
      dk = "Hide";
      kn = "Auto";
      cw = "Stand";
      ad = "by";
      dx = "Lock";
      ku = "Unlock";
      oc = "Seri number";
      rl = "Card code";
      gm = "On";
      d = "Off";
      ax = "Open link";
      rw = "Charge";
      pp = "Active";
      v = "Config";
      ng = "Delete";
      kl = "View";
      oj = "Continue";
      ic = "Inventory code";
      dj = "Scratch card";
      ik = "Next";
      js = "Use";
      nk = "Sort";
      fb = "Throw it away";
      bj = "Split";
      cz = "Equipment has been split, you get ";
      nt = "Yes";
      jv = "Get out";
      lt = "Get out";
      ga = "Withdraw coins";
      rg = "Store coins";
      cm = "Transfer coins";
      bv = "Store";
      kj = "Sell";
      dz = "Sell more";
      ok = "Sell all";
      dn = "Price";
      hn = "Buy";
      kx = "Buy more";
      mm = "No";
      bs = "Exit";
      g = "Chat";
      nd = "OK";
      ou = "Account";
      jp = "Password";
      gx = "Re-input";
      pl = "Account";
      lb = "Pass";
      eh = "re";
      ey = "Please restart game";
      hs = "Re-input password";
      ce = "Remember";
      iu = "Uncheck";
      cl = "Register";
      mq = "High Graphic";
      kk = "Low Graphic";
      jl = "Please input account name";
      by = "Account does not allow special characters.";
      gi = "You haven't added a password.";
      oy = "Your passwords do not match.";
      mn = "Account name must have at least five characters";
      jd = "Wrong password.";
      og = new String[] { "To register with name", "you have to follow the game rule." };
      jh = "What operator are you using? (You can recheck it in Menu)";
      dq = "Are you using your phone number to create account ?";
      aw = "private message";
      fu = new String[] { "message clan, group", "clan messages", "group message" };
      dl = "escort";
      re = "Plus";
      jq = "Plus more";
      rx = "potential point";
      o = "Accept";
      gk = "Cancel";
      oa = "List";
      nf = "Time";
      ab = "Achievement";
      gq = "Max";
      rv = "Accumulate";
      ls = "Connecting";
      nb = "Registering";
      df = "Logging";
      pb = "Not finished";
      ri = "Time to finish";
      ow = "Teamwork";
      jt = "Select";
      iy = "Uncheck";
      mv = "Select items to view the information.";
      os = "Assign";
      nl = "Result";
      y = "Review";
      f = "Level";
      ib = "Level";
      mz = "Do you want to exit?";
      qh = "Please rename your character";
      bt = "This server is maintained or overloaded. Please try again later or choose another server.";
      qu = "Create";
      dw = "Name";
      pi = "Name of character you want to friend";
      mo = "Friend link successful.";
      ep = "Loading... ";
      doa = "Close";
      qg = "Get reward";
      oq = "lucky gift";
      ez = "Inventory was expanded";
      ot = "Distance too far for escort, quest failed";
      rp = "The escort was wounded, quest failed";
      ph = "forever";
      pd = "Not upgrade";
      ba = "Can not upgrade.";
      ej = "Use special items to upgrade";
      bd = "Train";
      cs = "Stone train successful, you get";
      bh = new String[] { "Just transfer same type equipment", " or higher.", "Will lock fitted after transformation.." };
      io = "failure, you get";
      mh = "Message sent, please wait for confirmation.";
      ho = "Can not send message. Please check you balance or restart the game.";
      gb = "Sending Coins";
      rj = "Start";
      ja = "Choose at least 2 stones or more";
      ms = "Choose the equipment that you want to split the Stone";
      md = "Choose item and coins to exchange";
      no = "Move to luggage to choose";
      sb = "Change";
      ck = "Cell";
      sj = "Cells";
      im = new String[] { "Key Q", "Key W", "Key E" };
      fe = new String[] { "Key 7", "Key 8", "Key 9" };
      ke = new String[][] { { "tomboy", "with brooch", "pony tail", "curly" }, { "head band", "afro", "samurai", "spike" } };
      qy = new String[] { "Inventory", "Skill", "Potential", "Info", "Equipment", "Mounts" };
      di = new String[] { "Costume shop", "Inventory" };
      b = new String[] { "Cap", "Inventory" };
      kz = new String[] { "Cloth", "Inventory" };
      ag = new String[] { "Gloves", "Inventory" };
      hx = new String[] { "Pants", "Inventory" };
      eg = new String[] { "Shoes", "Inventory" };
      rb = new String[] { "Necklace", "Inventory" };
      qf = new String[] { "Ring", "Inventory" };
      fc = new String[] { "Gems", "Inventory" };
      lo = new String[] { "Charms", "Inventory" };
      lh = new String[] { "Weapons", "Inventory" };
      nv = new String[] { "Medicine", "Inventory" };
      ac = new String[] { "Medicine", "Inventory" };
      pr = new String[] { "Food", "Inventory" };
      bx = new String[] { "Food", "Inventory" };
      rd = new String[] { "Upgrade", "Inventory" };
      mt = new String[] { "Stand", "Inventory" };
      dd = new String[] { "Transfer", "Inventory" };
      a = new String[] { "Training Stone", "Inventory" };
      ll = new String[] { "Inventory", "Inventory" };
      cc = new String[] { "Shop", "Book Store", "Fashion Store", "Clan Store" };
      cv = new String[] { "Split Stone", "Inventory" };
      ih = new String[] { "Trade", "Inventory" };
      qc = new String[] { "Upgrade essence", "Inventory" };
      nz = new String[] { "Add attributes", "Inventory" };
      nr = new String[] { "Enhance equipment", "Inventory" };
      jm = new String[] { "Socketing", "Inventory" };
      kh = new String[] { "Leveling gem", "Inventory" };
      hj = new String[] { "Gem Roasting", "Inventory" };
      kg = new String[] { "Extract gem", "Inventory" };
      dp = new String[] { "Completed quest", "Inventory" };
      ia = new String[] { "Pickup", "Inventory" };
      { "Del" }[sk[3]] = "Inventory";
      hc = "Delete";
      ah = "Add";
      fy = "I will help decrease bad options of this gem.";
      ie = "I will help you extract gem from this item.";
      lf = new String[] { "- Use kin incase not enough coin", "- Move to inventory to choose stone", "- Amount of stones from 2 to 24" };
      eb = new String[] { "- Use coin incase not enough kin", "- Upgrading need Gold bar", "- Choose Equiptment and stone only", "Your equipment has reached max level" };
      fk = new String[] { "- Use coin incase not enough kin", "- Choose Equiptment and Gem" };
      da = "Lock Transfer";
      lr = "- Train Stone to level";
      is = "- Need: # kin";
      bf = "- Need: # Gold bars";
      rz = "- Need: # coins";
      eq = "- Percentage of success.";
      lg = "(success ";
      qn = "Add";
      it = "Locked";
      ec = "Killed";
      lq = "Arrest Beast";
      kw = "Kill Elitez";
      iq = "Kill Chief";
      ft = "Protect the child";
      cx = "No lock";
      nj = "Expires";
      ir = "Price: # kin";
      eu = "Price: # coins";
      ee = "Price: # clan coins";
      qx = "Price: # kin";
      ml = "Price: # gold bars";
      om = "Gold bar";
      c = "Do not have";
      du = "Next level: level #";
      jz = "Current level: level #";
      lj = "Maximum level";
      nh = "Reached maximum level";
      he = "Require: level";
      gz = "Class: ";
      gv = new String[] { "Main quest", "Sub quest" };
      et = "Quest";
      sd = "Obtain quest at";
      bn = "White Side";
      ol = "Black Side";
      mu = "Neutral";
      px = "team";
      q = "Find team";
      my = "Your current aggressive points are ";
      cu = new String[] { "Friends", "Hostile" };
      hf = "You are not friends with anyone";
      ma = "waiting confirmation";
      gc = "added you to friends list";
      ifa = "You have added";
      hr = "to the list";
      gh = "You and";
      rn = new String[] { "store", "Myself", "Map", "General", "Exit", "Jewellery", "Feature", "Pharmaceutical Key", "Pharmacy", "Grocery Key", "Grocery", "Strengthen", "Training", "Training key", "Inventory", "Split Equipment", "Area", "Trade", "Message" };
      iw = new String[] { "Passive Support", "Active use", "Active use", "Active use", "Active use" };
      bu = new String[] { "Character: ", "Agressive: ", "Level: ", "Class: ", "", "HP:", "MP: ", "Speed: ", "Attack: ", "Anti Fire: ", "Anti Ice: ", "Anti Wind: ", "Reduce Pain: ", "Accurate point:", "Dodge ability: ", "Critical: ", "Close combat strike back: ", "Anti chakra: ", "Anti chakra back: ", "Action points: " };
      qs = " times";
      kv = new String[] { "Genin", "Chunin", "Jounin", "Kage" };
      ro = new String[] { "Action point: ", "Weapon Fame: ", "Necklace Fame: ", "Ring Fame: ", "Gems Fame: ", "Charm Fame: ", "Hat Fame: ", "Cloth Fame: ", "Gloves Fame: ", "Pants Fame: ", "Shoes Fame: ", "Accomplish daily quest: ", "Arrest Beast: ", "Read the basic potential book: ", "Read the basic skill book: ", "Clan: ", "Cave time left: ", "Star Fame: ", "Wind Thunder Mooncake: ", "Ice Fire Mooncake: " };
      au = new String[] { "Name: ", "Gender: ", "Hair: " };
      me = new String[] { "Female", "Male" };
      bz = new String[] { "Strength", "Dexterity", "Constitution", "Chakra" };
      jc = "You were not killed by anyone.";
      oh = "You won #.";
      mi = "You lost #.";
      al = "Your fight match between you and # is over.";
      lx = new String[] { "", "Elitez", "Chief", "Beast" };
      ev = " try to kill you";
      hy = "Potential point";
      er = "Skill point";
      ay = "Not enough MP to use";
      rf = "Only select unlocked items";
      cq = "Only select unlocked items that haven't expired";
      ps = "Just choose Stones to train";
      oo = "Just choose Stone, Equipment and upgrade insurance.";
      lp = "Just choose Equipment and conversion items.";
      ko = "Can not upgrade";
      jx = "Maximum upgrade";
      cr = "Only upgraded item or equipment to split.";
      rh = "Items for Trading are full.";
      ky = "Amount is Full.";
      se = "Not enough points.";
      cb = "Please input added points.";
      hi = "You need to input card information.";
      in = "You need to input card value information.";
      ff = "You need to enter serial number.";
      lm = "You need to enter topup times.";
      dt = "You need to enter a name";
      iz = "Enter Points";
      ct = "Enter Coins";
      ed = "Enter quantity";
      fv = "Username";
      qm = "Coin";
      kf = "Kin";
      ru = "Gold bar";
      n = "Put in inventory";
      hq = "Do you really want to dismissed this one?";
      fn = "Expulsion of members will reduce Clan budgets (see details in Kanata NPC). Do you want to dismiss them?";
      sa = "Leaving clan will reduce your coins (see Kanata for details.)  Are you sure you want to leave?";
      bq = "After using this item, it will be locked. Do you want to use it?";
      fd = "Sold items can not be recovered. Do you want to sell this item?";
      ak = new String[][] { { "cap" }, { "wea", "pon" }, { "cloth" }, { "neck", "lace" }, { "glo", "ves" }, { "ring" }, { "pants" }, { "gems" }, { "shoes" }, { "charm" }, { "pet" }, { "mask" }, { "ninja", "yoroi" }, { "clan", "item" }, { "Emp", "ty" }, { "Ancient", "Book" }, { "Ar", "mor" }, { "Sad", "dle" }, { "Tas", "sels" }, { "Coro", "net" }, { "Eng", "ine" }, { "Sat", "nav" }, { "ECU", "" }, { "N20", "" } };
      mg = new String[] { "Not a student", "School: Hirosaki", "School: Ookaza", "School: Haruna" };
      oe = new String[] { "", "Attribute: Fire", "Attribute: Water", "Attribute: Wind", "", "", "" };
      bp = "You got";
      ox = "You have not entered the amount of gold bars.";
      ao = "Can not sell upgraded equipment.";
      af = "You don't have enough coins to move.";
      nu = "You don't have enough coins to store.";
      mp = "You don't have enough coins to withdraw.";
      gn = "You don't have enough gold bars to sell.";
      qo = new String[] { "Success,  equipped with level up ", "failed, return level of equipment", "equipment upgraded maximum", "equipment level" };
      ld = new String[] { "Success socketing", "Socketing has failed" };
      kp = "month";
      ex = "week";
      jn = "day";
      ei = "hour";
      dm = "second";
      qk = ",minute";
      iv = "Number of target";
      qa = "Range";
      na = "MP cost";
      ap = "Cool down time";
      nw = "You need at least two stones to train.";
      qd = "Gender does not match";
      sg = "Don't have any one else";
      cf = "Your level is too low";
      fz = "Stone has reached the maximum level";
      ca = "Your stones after leveling will be blocked. Would you like to continue?";
      fl = "You don't have enough coins to level stone";
      hb = "You don't have enough gold bars to upgrade equipment";
      ai = "You don't have enough coins to upgrade equipment";
      dr = "Many training stones will be wasted. Are you sure you want to upgrade";
      kd = "After upgrade this item will be locked. Do you want to continue?";
      aj = "Can not split the unupgraded item.";
      ip = "Your luggage doesn't have enough space.";
      gr = "Do you really want to split this item?";
      ka = "Do you really want to convert?";
      li = "Welcome to trading. Do you want to trade?";
      bm = "Welcome to the clan. Do you want to join Clan '#' ?";
      dg = "Do you want to join this clan?";
      ij = "wants to fight with you. Do you accept?";
      gl = "invite you to Party. Do you want to join?";
      cn = "ask you to join their Party. Do you accept?";
      ix = "Convert successful.";
      mr = new String[] { "Gender: Female", "Gender: Male" };
      ni = "Area";
      fx = "Population";
      po = "Party";
      np = "At this moment, you have not joined any Party.";
      bl = "times";
      hm = new String[] { "Info", "Member", "Warehouse", "Statistic", "Guardian" };
      ly = new String[] { "Clan: ", "Clanmaster: ", "Member: ", "Level: ", "Experience: ", "Budget: ", "Establish: ", "Donation: ", "Maintenance fee: ", "Upgrade fee: ", "Enter the Territory of Clan: remain ", "Week donation: ", "Use Clan card mark: remain " };
      oz = new String[] { "Coins at", "Establish clan, budget has", "expulsion, budget decrease", "clan contribution, budget increase", "withdraw clan budget, budget decrease", "Fee for maintain clan, budget decrease", "upgrade clan, budget decrease" };
      ju = "You are not a member of any clan";
      fh = "Send to Clan Member";
      gj = new String[][] { { "Hirosaki School" }, { "Haruna School" }, { "Ookaza School" }, { "Village", "Kojin village", "Sanzu village", "Tone village", "Fish Village", "Chakumi Village", "Echigo Village", "Oshin Village" }, { "Area" } };
      eo = new String[] { "Cap", "Ring", "Cloth", "Necklace", "Gloves", "Ring", "Pants", "Gems", "Shoes", "Charm" };
      bb = new String[] { "Active hidden", "Active level" };
      ht = new String[] { "", "Fire", "Water", "Wind" };
      fs = new String[] { "Character", "Level", "Jewellery" };
      ea = "You do not have any special skills.";
      r = "You do not have any special weapons. Go to Menu/Status/Equipment to check";
      jf = "This item was locked.";
      ar = "Items, accessories and stones";
      lv = "price (coin)";
      hv = "price (kin)";
      ln = "You are hungry, eat some more";
      l = "You level is too low to use this item";
      nq = "Out off MP";
      mk = "Out off HP";
      j = new String[] { "Trade", "Fight", "Berserker", "Add friend", "Invite to Party", "Recover", "Check info", "Private chat", "Invite to clan", "Request to join clan", "Block request to joint clan", "Auto recover", "Cấm Chat" };
      qe = "You are in ";
      ef = new String[] { "Let's find", " at ", " to get the quest.", "You have finished all quests this version, please wait for the next version." };
      od = new String[] { "Exhausted", "Starring", "Come back", "Revive now (1 Gold bar)" };
      rs = "After joining a class, you can receive any quest from the principal.";
      bo = "Create team";
      fo = "Leave team";
      ch = "Teamleader";
      t = "Lock team";
      of = "Unlock team";
      qr = "Ask to join party.";
      id = "Refresh";
      il = "You are not a member of any team.";
      kr = "Empty information.";
      at = "Cannot find any Party now.";
      sf = new String[] { "PK normal", "PK team", "PK clan", "PK Berserker" };
      qv = new String[] { "PK status", "Friend", "Enemy", "Party", "Find party", "Clan", "Protect account", "Auto", "Sell Shinwa", "Upgrade essence", "Enhance equipment", "Add attributes" };
      dv = new String[] { "Map", "Quest", "Clan" };
      aa = new String[] { "Clan Master", "Chief Elder", "Elder", "Elite", "Member" };
      bc = new String[] { "(CM)", "(CE)", "(ED)", "(EL)" };
      kq = new String[] { "Online only", "Left", "Notice ", " Contribute ", " Withdraw funds ", " Upgrade ", " Invite to territory ", "Unlock" };
      fi = "Sort by dedicating week";
      qq = new String[] { "Expulsion", "Transfer", "Make friend" };
      si = " You are promoted to team leader.";
      jk = "You were kicked off of team.";
      ql = "Invite to team";
      go = "Add";
      av = "Inappropriated Weapons.";
      ds = "Do you want to delete this person from your friend list?";
      pw = new String[] { "Go to school to upgrade your marks." };
      mf = new String[] { "Strength = Attack", "Dexterity = dodge, accurate", "Strength = HP", "Chakra = MP" };
      db = new String[] { "No need to upgrade strength", "Dexterity = dodge, accurate", "Strength = HP", "Chakra = Attack, MP" };
      op = "Close current tab.";
      ov = new String[] { "Public chat", "You can chat with people around you here." };
      fp = new String[] { "Same party", "You can chat with your Party member here." };
      cj = new String[] { "Global chat", "You will lose 5 Gold Bars for each use.", "This message will broadcast to everybody.", "Your account will automatically be locked if you attempt to advestise any wap website, or use profanity." };
      en = new String[] { "Clan", "Yon can chat with Clanmates in this place" };
      em = "Block global chat: ";
      jb = "Block private chat: ";
      ae = "Appoint";
      nc = "Dismiss";
      ra = "Expulsion";
      hw = "Maximum 6 digits.";
      mj = "Just allow number digit for protected password.";
      k = "Protected password can not start with number 0.";
      jr = "Wrong password.";
      aq = "To use this function, you have to have Multi Teleport Card.";
      gf = "To activate this function, you have to pay 10.000 kin. Do you want to activate?";
      rt = "Password";
      sh = "input the mobile number that you want to register";
      mc = "You did not input the number that you used to register this game before.";
      jg = "To get the password for account '#'. You must use the phone number used to register this account.";
      u = "Change pass";
      cg = "Cancel protection";
      fq = "Old password";
      lk = "New password";
      cy = "You have learned ";
      ks = "Input your message content";
      pk = "Input the amount of coin to withdraw";
      pj = "Input the coin amount to donate to the Clan.";
      lw = "Input type of card and value";
      fr = "Input serie number and time of charging.";
      az = "Input amount of split time.";
      kt = "Value";
      sc = "Type of card";
      qi = "Seri number";
      pz = "Time of charging";
      fg = "Block message";
      mx = "Submit this bug to Admin.";
      an = new String[] { "Assign key", "Assign to 5 key" };
      gg = "Send message success.";
      kc = "Congratulations! your choice is correct.";
      es = "Can not send message.";
      be = "Send failure.";
      pg = "Not enough coin to contribute";
      hd = "The amount to split is invalid.";
      fa = "invalid input value.";
      qw = "Do you want to cancel Protect account function?";
      hg = "wants to challenge you in the battle arena. Do you agree?";
      pe = "Sort by price";
      pq = "Sort by level";
      s = "Sort by name";
      p = "Item is sent for trading";
      ne = "Trading fee is 5.000 coin";
      ii = "Do you want to sell item with # coins ?";
      qp = "Do you want to buy item with # coins ?";
      rk = "Seller";
      gy = "remain";
      jo = "a few";
      ha = "seconds";
      nm = new String[] { "Stone", "Cap", "Weapon", "Cloth", "Necklace", "Gloves", "Rings", "Cloths", "Gems", "Shoes", "Charms", "Miscellaneous" };
      hl = "pay 1% of value as tax";
      ge = "Experience";
      or = "Announcement";
      oi = "Invite friends";
      on = "Choose card";
      rc = "Flip remaining: ";
      ob = "Challenges you and your clan. Do you agree ?";
      hh = "Max options";
      w = "Invite this person";
      pf = "Invite all";
      el = "'#' invites you to join the clan war. Do you want to join?";
      i = "Input member's name";
      je = new String[][] { { "Requirement: Clan level 5", "Cost to Open: 1.000.000 clan coins." }, { "Requirement: Clan level 10.", "Cost to Open: 5.000.000 clan coins." }, { "Requirement: Clan level 15.", "Cost to Open: 10.000.000 clan coins." }, { "Requirement: Clan level 20.", "Cost to Open: 20.000.000 clan coins." }, { "Requirement: Clan level 25.", "Cost to Open: 30.000.000 clan coins." } };
      mw = new String[] { "HP: ", "MP: ", "Using food level: ", "Always using skill to support", "Dùng khiên mana", "Dùng đốt quái", "Dùng phân thân", "Pick up Kins", "Pick up Hp, MP", "Pick up Material", "Luyện đá Max", "Nhặt Trang Bị", "Nhặt Trang Bị Lạ", "Nhặt VP Nhiệm Vụ", "Nhặt VP Sự Kiện", "Nhặt All", "Nhặt SVC", "Not picked up", "Auto TTT", "AutoTTC", "ReMap", "Tàn sát map trống", "Auto Mua Thức Ăn", "TS khi hết MP", "Auto Reconnect", "Next Map Null Boss", "Săn TATL", "Hit Normal", "Hit Elitez", "Hit Chief", "Cộng tiềm năng", "Cộng kĩ năng", "Đánh theo nhóm", "Né PK", "Dùng Cổ Lệnh", "Mua Cổ Lệnh" };
      lz = "Use button < and > to change value";
      de = "Touch to change value";
      mb = "Distance is very far, Can not heal another people";
      ek = "Percent value is from 10 to 90";
      hp = new String[] { "Level 1", "Level 10", "Level 20", "Level 30", "Level 40", "Level 50", "Level 60", "Level 70" };
      bk = new String[] { "Level 1", "Level 2", "Level 3", "Level 4", "Level 5", "Level 6", "Level 7", "Level 8", "Level 9", "Level 10", "Level 11", "Level 12" };
      hk = "Account required password, input password to unlock.";
      qb = "Vitality";
      pv = "Name of mounts";
      ji = new String[] { "Upgrade essence by using 9 essences", "of the same kind or 3 common essences", "and stone level 11 or 3 rare essences and stone level 12." };
      x = "Only common essence and rare essence";
      bg = "Only stone and essence to upgrade essence";
      pt = "Just only 1 stone to upgrade";
      dy = "Need to use 3 rare essences and stone level 12 or 3 common essences and stone level 11";
      as = "Have to use stone level 11 and 12";
      z = "Have to use essences of the same kind";
      bi = "Have to has 3 essences to Upgrade";
      m = "Essences are excessive";
      pu = "This equipment can not Enhance";
      bw = "Not enough material";
      qz = "This function is not available for this equipment";
      pn = "Save candy";
      h = "Enhance level";
      jy = "Engine";
      le = "Fuel";
      hz = "Give candy";
      ny = new String[] { "essence", "essence", "common essences", "rare essences" };
      e = "Equipment enhanced to max level already";
    }
  }
  
  /* Error */
  private static String a(String paramString)
  {
    // Byte code:
    //   0: new 1566	java/lang/StringBuffer
    //   3: dup
    //   4: ldc 75
    //   6: invokespecial 2087	java/lang/StringBuffer:<init>	(Ljava/lang/String;)V
    //   9: aload_0
    //   10: invokevirtual 2088	java/lang/StringBuffer:append	(Ljava/lang/String;)Ljava/lang/StringBuffer;
    //   13: invokevirtual 2089	java/lang/StringBuffer:toString	()Ljava/lang/String;
    //   16: invokestatic 2079	df:a	(Ljava/lang/String;)Ljava/io/InputStream;
    //   19: astore_0
    //   20: aload_0
    //   21: invokevirtual 2082	java/io/InputStream:available	()I
    //   24: newarray <illegal type>
    //   26: astore_1
    //   27: aload_0
    //   28: aload_1
    //   29: invokevirtual 2083	java/io/InputStream:read	([B)I
    //   32: ldc 1
    //   34: invokevirtual 2086	java/lang/String:length	()I
    //   37: pop2
    //   38: new 1565	java/lang/String
    //   41: dup
    //   42: aload_1
    //   43: ldc_w 1214
    //   46: invokespecial 2085	java/lang/String:<init>	([BLjava/lang/String;)V
    //   49: astore_0
    //   50: ldc 1
    //   52: invokevirtual 2086	java/lang/String:length	()I
    //   55: pop
    //   56: ldc 4
    //   58: invokevirtual 2086	java/lang/String:length	()I
    //   61: ifge +14 -> 75
    //   64: aconst_null
    //   65: areturn
    //   66: ldc 1
    //   68: invokevirtual 2086	java/lang/String:length	()I
    //   71: pop2
    //   72: ldc 1
    //   74: astore_0
    //   75: aload_0
    //   76: areturn
    // Local variable table:
    //   start	length	slot	name	signature
    //   0	77	0	paramString	String
    //   26	17	1	arrayOfByte	byte[]
    //   66	1	2	localException	Exception
    // Exception table:
    //   from	to	target	type
    //   20	50	66	java/lang/Exception
  }
  
  private static void e()
  {
    sk = new int[37];
    sk[0] = "   ".length();
    sk[1] = ((0x4 ^ 0xB) & (0x2E ^ 0x21 ^ 0xFFFFFFFF));
    sk[2] = (0xDE ^ 0xAC ^ 0xEA ^ 0x9E);
    sk[3] = " ".length();
    sk[4] = "  ".length();
    sk[5] = (0x1A ^ 0x1E);
    sk[6] = (0x38 ^ 0x0 ^ 0x2 ^ 0x3F);
    sk[7] = (0x5B ^ 0x55);
    sk[8] = ('²' + 106 - 124 + 26 ^ '¥' + '' - 211 + 103);
    sk[9] = (0x79 ^ 0x71);
    sk[10] = (0xB1 ^ 0xB8);
    sk[11] = (0x49 ^ 0x43);
    sk[12] = (74 + 45 - 94 + 125 ^ 40 + 91 - 26 + 52);
    sk[13] = (0x17 ^ 0x2B ^ 0x14 ^ 0x24);
    sk[14] = (0x25 ^ 0x54 ^ 0x4C ^ 0x30);
    sk[15] = (0x22 ^ 0x7C ^ 0x56 ^ 0x1C);
    sk[16] = (31 + 112 - 46 + 42 ^ 33 + 46 - 56 + 109);
    sk[17] = (0xF3 ^ 0xB6 ^ 0xF3 ^ 0xA6);
    sk[18] = (0xBE ^ 0xAF);
    sk[19] = (0x94 ^ 0x8A ^ 0x24 ^ 0x28);
    sk[20] = (40 + 86 - -1 + 37 ^ '³' + 124 - 244 + 124);
    sk[21] = (60 + 43 - 79 + 130 ^ 53 + 74 - 77 + 80);
    sk[22] = (0xFA ^ 0xA8 ^ 0xE8 ^ 0xAF);
    sk[23] = (0x97 ^ 0x81);
    sk[24] = (0x5E ^ 0x32 ^ 0xCF ^ 0xB4);
    sk[25] = (0x9D ^ 0xB9);
    sk[26] = (0x39 ^ 0x5D ^ 0x6F ^ 0x12);
    sk[27] = (0xDD ^ 0xC7);
    sk[28] = (0x3C ^ 0x5E ^ 0x63 ^ 0x1A);
    sk[29] = (78 + 106 - 170 + 148 ^ 91 + 25 - -9 + 65);
    sk[30] = (0x5A ^ 0xB ^ 0xF2 ^ 0xBE);
    sk[31] = (0x46 ^ 0x58);
    sk[32] = (0x8C ^ 0x93);
    sk[33] = (62 + 113 - 154 + 153 ^ 110 + 5 - 81 + 108);
    sk[34] = (0x97 ^ 0xB6);
    sk[35] = (0x58 ^ 0x39 ^ 0xC6 ^ 0x85);
    sk[36] = (0xF ^ 0x3E ^ 0xB2 ^ 0xA0);
  }
  
  public static void c() {}
  
  static
  {
    cs.a(60);
    c();
  }
  
  public static void d() {}
}


/* Location:              C:\Users\Admin\OneDrive\Documents\NSOv2_test.jar!\an.class
 * Java compiler version: 1 (45.3)
 * JD-Core Version:       0.7.1
 */